[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { eth = "https://eth-sepolia.public.blastapi.io", arb = "wss://arbitrum-sepolia-rpc.publicnode.com", zksync = "https://sepolia.era.zksync.dev"}

remappings=[
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@ccip/contracts/=lib/ccip/contracts",
    "@chainlink-local/=lib/chainlink-local"
]


[invariant]
runs = 500
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
